console.log("Hello! I'm your coding fun fact guide!");
let botName = "teacherBot";
let botLocation = "the universe";
let favoriteLanguage = "JavaScript";
console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is " + favoriteLanguage + ".");
let codingFact;
codingFact = "Did you know that " + favoriteLanguage + " was created in just 10 days?";
console.log(codingFact);
codingFact = favoriteLanguage + " can run both in the browser and on servers!";
console.log(codingFact);
codingFact = "Many developers love " + favoriteLanguage + " for its flexibility.";
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");
